# Links to neccessary data downloads:
* [deepsolar site](https://web.stanford.edu/group/deepsolar/home)
* []()

# Links to neccessary data downloads:
### DeepSolar Data
> * Created by a research team at Stanford University: [DeepSolar Site](http://web.stanford.edu/group/deepsolar/home)

## NREL SEEDS (Solar Energy Evolution and Diffusion Studies: 2017-2019)  II Data
* Can be found on the : [NREL SITE](https://www.nrel.gov/solar/seeds/2017-2019-study.html)

In [1]:
import pandas as pd
import numpy as np
from _products.utility_fnc import blocking_sound_player as bsp, Alert_sounds
# _products/_interface_tools.py
from _products._interface_tools import *
from _DATAGEN_TOOLS._DataConvergenceTools import *
pd.options.mode.use_inf_as_na = True
import datetime
import PySimpleGUI as sg
import time

In [2]:
today = datetime.date.today()
today

datetime.date(2021, 11, 3)

In [3]:
regions=None

# left as is will store a file called test_merge.csv in the same directory as this file
dest_pth='test_merge.csv'

tstart = time.time()
cdg = CONVERGENT_DATA_GEN( 
                         destination=dest_pth,  
                         deepsolarpath='../_Data/DeepSolar/deepsolar_tract2.xlsx',
                         seedspath=r'../_Data/NREL/seeds_ii_replica.csv',
                         usecols=(None, None), 
                         generate_extra_variables=True,
#                          generate_extra_variables=False,
                        )



print("The data generation took: {} secs".format(time.time() - tstart))

the 0.949 percentile of number_of_solar_system_per_household is 0.05468725670000001
the 0.949 percentile of PV_HuOwn is 0.12629228190767114
the 0.949 percentile of AvgSres is 36.54661476592
		NT3:
		T3:
		West:
		WestNT3:
		Mid West:
		South:
		NorthEast:
The data generation took: 169.1058487892151 secs

# Take a look a the merged data set.

In [9]:
display(cdg.merged)

,tile_count,solar_system_count,total_panel_area,fips,average_household_income,county,education_bachelor,education_college,education_doctoral,education_high_school_graduate,...,Top_3_States,Savings_potential,Income_x_College_Edu,Cost_x_Consumption,urban_diversity,suburban_diversity,rural_diversity,High_Solar_Areas,Low_Solar_Areas,DS_HighSolar
0,0,0,0.000000,27145011200,70352.78987,Stearns County,569,1690,13,1757,...,0.0,39293.966008,23868.091499,163.378541,0.00000,0.0,0.046960,0.0,1.0,0.0
1,25,21,1133.436461,27145011301,61727.08520,Stearns County,674,1434,108,767,...,0.0,NaN,20204.260409,142.741048,0.00000,0.0,0.145934,0.0,0.0,0.0
2,3,3,64.505776,27145011302,71496.88658,Stearns County,854,1459,31,1541,...,0.0,38524.800104,20632.800232,142.741048,0.00915,0.0,0.000000,0.0,1.0,0.0
3,0,0,0.000000,27145011304,86840.15275,Stearns County,640,1116,68,1095,...,0.0,33383.931869,23120.510441,83.731445,0.00000,0.0,0.187334,0.0,1.0,0.0
4,5,5,164.583303,27145011400,89135.31560,Stearns County,654,1314,15,982,...,0.0,33072.214869,26845.553744,83.731445,0.00000,0.0,0.090766,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72532,1,1,40.277124,8049000202,90163.61186,Grand County,1612,1419,3,1099,...,0.0,51028.438668,20907.177410,102.071999,0.00000,0.0,0.157526,1.0,0.0,1.0
72533,0,0,0.000000,40085094100,45124.15301,Love County,95,441,0,803,...,0.0,12834.023586,9961.708392,113.759579,0.00000,0.0,0.340763,1.0,0.0,1.0
72534,1,1,21.902255,40085094200,60878.45874,Love County,426,961,11,1343,...,0.0,25967.145124,14582.029572,108.034894,0.00000,0.0,0.300213,1.0,0.0,1.0
72535,0,0,0.000000,40085094300,56817.99687,Love County,134,355,5,571,...,0.0,9304.672543,14006.170505,108.034894,0.00000,0.0,0.151155,1.0,0.0,1.0
72536,3,2,224.947000,48327950300,50221.55626,Menard County,137,457,0,470,...,0.0,16312.691000,10161.321301,127.104536,0.00000,0.0,0.231210,1.0,0.0,1.0

# Some Descriptives

In [10]:
display(cdg.merged.describe())

,tile_count,solar_system_count,total_panel_area,fips,average_household_income,education_bachelor,education_college,education_doctoral,education_high_school_graduate,education_less_than_high_school,...,Top_3_States,Savings_potential,Income_x_College_Edu,Cost_x_Consumption,urban_diversity,suburban_diversity,rural_diversity,High_Solar_Areas,Low_Solar_Areas,DS_HighSolar
count,72537.000000,72537.000000,72537.000000,7.253700e+04,71651.000000,72537.000000,72537.000000,72537.000000,72537.000000,72537.000000,...,72537.000000,66663.000000,71580.000000,72265.000000,71940.000000,71940.000000,71940.000000,72537.000000,72537.000000,72537.000000
mean,30.255787,20.217958,1333.547680,2.794758e+10,73314.418095,536.095689,842.039621,38.138178,804.067193,387.468464,...,0.141569,24841.340461,16274.677492,110.052867,0.142611,0.106862,0.059607,0.395770,0.524243,0.286378
std,86.337406,54.229584,6103.442088,1.579265e+10,37650.268239,457.495174,483.540398,62.432598,470.637801,359.292471,...,0.348610,17046.797771,7829.880843,22.171081,0.218260,0.189168,0.128709,0.489019,0.499415,0.452071
min,0.000000,0.000000,0.000000,1.001020e+09,6910.984848,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,46.845787,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,11.669079,1.212709e+10,49507.381085,214.000000,506.000000,0.000000,465.000000,149.000000,...,0.000000,13065.033501,10391.269555,96.376683,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4.000000,3.000000,138.332615,2.716307e+10,64270.939490,411.000000,767.000000,17.000000,737.000000,284.000000,...,0.000000,21785.373743,15297.042940,107.893681,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,22.000000,14.000000,745.015408,4.104303e+10,86523.383305,739.000000,1086.000000,47.000000,1066.000000,510.000000,...,0.000000,32813.561988,21088.209913,127.104536,0.275771,0.151909,0.047795,1.000000,1.000000,1.000000
max,4468.000000,1535.000000,592031.075000,5.604595e+10,537130.215800,12753.000000,12487.000000,1395.000000,8765.000000,5453.000000,...,1.000000,418303.204018,89684.240233,262.413841,0.812441,0.790290,0.767776,1.000000,1.000000,1.000000

### Inside the convergent data object there is a dictionary titled DataDict that stores descriptions of all non-identifier and most identifier varialbes I have added. This can be viewed below

In [14]:

# print the name and description of the variables added to the merged set
for v in cdg.DataDict:
    print()
    print("'{}':\n{}".format(v, cdg.DataDict[v]))
    print()

'Green_Travelers':
combination of rates of persons using a bicycle, walkiing, or working from home


'low_commute_times':
 % persons commuting for 19 minuts or less (DEEPSOLAR)


'travel_time_40_89_rate':
% commuting between 40 and 89 minutes to work (DeepSolar)


'high_commute_times':



'travel_time_20_39_rate':
% commuting between 20 and 39 minutes to work (DeepSolar)


'locale_dummy':
numeric encodiing of locale: 1=rural, 2=town, 3=suburban, 4=urban


'locale_(rural)':
indicates a rural locale


'locale_(suburban)':
indicates suburban a rural locale


'locale_(town)':
indicates town a rural locale


'locale_(urban)':
indicates urban a rural locale


'URBAN':
aggregation of urban and town locales into the 'URBAN' locale


'Rural':
indicates urban a rural locale


'Suburban':
indicates urban a suburban locale


'net_metering_bin':
indication of presence of program (DeepSolar)


'property_tax_bin':
indication of presence of program  (DeepSolar)


'lowincome_tax_credit_bin':
indication of presence of program (SEEDSII)


'Policy_Combo':
indication of :
* 1 if there is only net metering
* 2 if there is only property tax
* 3 if there is only the low income tax credit
* 4 there is both property tax and net metering
* 5 there is both net metering and low income tax credit
* 6 there is both property tax and low income tax credit
* 7 if there is all three programs present


'renew_prod':
Renewable (overall) energy producation based on data from:ttps://www.eia.gov/electricity/data/state/


'hydro_prod':
hydro renewable energy producation based on data from:ttps://www.eia.gov/electricity/data/state/


'solar_prod':
solar renewable  energy producation based on data from:ttps://www.eia.gov/electricity/data/state/


'education_high_school_or_above_rate':
 percentage of persons high graduate education level or above (DeepSolar)


'education_high_school_or_below_rate':
percentage persons with high school education or less (DeepSolar)


'education_master_or_above_rate':
percentage persons with masters degrees or above (DeepSolar)


'education_bachelor_or_above_rate':
percentage persons with bachelor degress or above (DeepSolar)


'educated_population_rate':
population 25 or above with some college education (SEEDSII) / population (DeepSolar)


'hh_total':
 sum of 'hh_size_1', 'hh_size_2', 'hh_size_3', 'hh_size_4' counts from SEEDSII


'%hh_size_1':
 hh_size_1(SEEDSII) / hh_total(Derived)


'%hh_size_2':
 hh_size_2(SEEDSII) / hh_total(Derived)


'%hh_size_3':
 hh_size_3(SEEDSII) / hh_total(Derived)


'%hh_size_4':
 hh_size_4(SEEDSII) / hh_total(Derived)


'hu_1959toearlier':
'hu_vintage_1940to1959' (SEEDSII) * 'hu_vintage_1940to1959'(SEEDSII)


'hu_1959toearlier_pct':
'hu_1959toearlier' (derived) * 'housing_unit_count'(DeepSolar)


'hu_1960to1979_pct':
'hu_vintage_1960to1970' (SEEDSII) * 'housing_unit_count'(DeepSolar)


'hu_1980to1999_pct':
'hu_vintage_1980to1999' (SEEDSII) * 'housing_unit_count'(DeepSolar)


'hu_2000toafter':
'hu_vintage_2000to2009 (SEEDSII) * 'hu_vintage_2010toafter'(SEEDSII)


'hu_2000toafter_pct':
'hu_2000toafter' (SEEDSII) * 'housing_unit_count'(DeepSolar)


'Mid_Agedwellings':
'hu_vintage_1960to1970' (SEEDSII) * 'hu_vintage_1980to1999'(SEEDSII)


'hu_own_pct':
number of home owners (SEEDSII) * number of housing units % (DeepSolar)


'net_metering_hu_own':
new metering years (DeepSolar) * homeowner % (SEEDSII)


'property_tax_hu_own':
property tax years (DeepSolar) * homeowner % (SEEDSII)


'incent_cnt_res_own':
incentive_count_residential(DeepSolar) * homeowner % (SEEDSII)


'med_inc_ebill_dlrs':
average monthly energy bill (SEEDSII) * median household income(SEEDSII)


'avg_inc_ebill_dlrs':
average monthly energy bill (SEEDSII) * averages household income(DeepSolar)


'dlrs_kwh x median_household_income':
dollars / kWh (DeepSolar) * median household income(DeepSolar)


'own_popden':
population_density (DeepSolar) * hu_own_pct (SEEDSII)


'female_pct':
population of female / (population females + population males) (SEEDSII)


'male_pct':
population of male / (population females + population males) (SEEDSII)


'Gender_Ratio':
'pop_female' / 'pop_male' (SEEDSII)


'white_pct':
'pop_caucasian'/ 'population' (SEEDSII)


'black_pct':
'pop_african_american'/ 'population' (SEEDSII)


'asian_pct':
'pop_asian'/ 'population' (SEEDSII)


'hispanic_pct':
'pop_hispanic'/ 'population' (SEEDSII)


'SRpcap':
total residential installations / population (DeepSolar)


'SNRpcap':
total non-residential installations / population (DeepSolar)


'ST_pcap':
total installations / population (DeepSolar)


'SRaPa':
residential area by total panel area (DeepSolar)


'SNRaPa':
nonresidential area by total panel area (DeepSolar)


'SRaPcap':
residential installation area /total population


'SNRaPcap':
non-residential installation area /total population


'PV_HuOwn':
residential installations per home owner (DeepSolar/SEEDSII)


'AvgSres':
residential installation panel area / total residential installations


'Hot_Spots_hh':
indicates that the census tract is in the 95th percentile for per household adoption


'Hot_Spots_hown':
indicates that the census tract is in the 95th percentile for per homeowner adoption


'Hot_Spots_AvgAr':
indicates that the census tract is in the 95th percentile average panel area


'age_25_44_rate':
ages between 25 to 44 (DeepSolar)


'age_25_64_rate':
ages between 25 to 64 (DeepSolar)


'age_55_or_more_rate':
ages between 55 or above (DeepSolar)


'age_minor_rate':
ages between 5 and 17 (DeepSolar)


'age_zoomer_rate':
ages between 5 to 24 (DeepSolar)


'high_own_hh':
'high_own_hh' high income owned homes (SEEDSII)


'mid_own_hh':
mid income owned homes (SEEDSII)


'mod_own_hh':
moderate income owned homes (SEEDSII)


'low_own_hh':
low income owned homes (SEEDSII)


'verylow_own_hh':
very low income owned hoomes (SEEDSII)


'total_own_hh':
total owned homes (SEEDSII)


'total_sf_own_hh':
total single family owned homes (SEEDSII)


'total_mf_own_hh':
total multifamily owned homes (SEEDSII)


'high_hh_rate':
rate of high income owned homes (SEEDSII)


'mid_hh_rate':
rate of mid income owned homes (SEEDSII)


'mod_hh_rate':
rate of moderate income owned homes (SEEDSII)


'low_hh_rate':
rate of low income owned homes (SEEDSII)


'very_low_hh_rate':
rate of very low income owned homes (SEEDSII)


'high_own_Sbldg':
high income owned homes suitable for solar installations (SEEDSII)


'mid_own_Sbldg':
mid income owned homes suitable for solar installations (SEEDSII)


'mod_own_Sbldg':
moderate income owned homes suitable for solar installations (SEEDSII)


'low_own_Sbldg':
low income owned homes suitable for solar installations (SEEDSII)


'verylow_own_Sbldg':
verylow owned homes suitable for solar installations (SEEDSII)


'total_own_Sbldg':
total owned homes suitable for solar installations (SEEDSII)


'high_own_Sbldg_rt':
% high income owned homes suitable for solar installations (SEEDSII)


'mid_own_Sbldg_rt':
% mid income owned homes suitable for solar installations (SEEDSII)


'mod_own_Sbldg_rt':
% moderate income owned homes suitable for solar installations (SEEDSII)


'low_own_Sbldg_rt':
% low ncome owned homes suitable for solar installations (SEEDSII)


'verylow_own_Sbldg_rt':
% very low income owned homes suitable for solar installations (SEEDSII)


'Tot_own_mw':
Total owned generation capacity (SEEDSII)


'Yr_own_mwh':
Total annual generatio potential (SEEDSII)


'high_own_mwh':
high income owned generation potential (SEEDSII)


'mid_own_mwh':
mid income owned generation potential (SEEDSII)


'mod_own_mwh':
moderate income owned generation potential (SEEDSII)


'low_own_mwh':
low income owned generation potential (SEEDSII)


'verylow_own_mwh':
verylow income owned generation potential (SEEDSII)


'high_own_elep_hh':
high income owned electrical price by household (SEEDSII)


'mod_own_elep_hh':
moderate income owned electrical price by household (SEEDSII)


'low_own_elep_hh':
low income electrical prices (SEEDSII)


'verylow_own_elep_hh':
very low income owned electrical price by household (SEEDSII)


'total_own_elep':
total owned electrical price (SEEDSII)


'Yrl_savings_$':
dollars_per_kwH (DeepSolar) / yearly possible genartion potential (SEEDSII)


'Yrl_%_inc':
yearly savings / average income


'Yrl_%_$_kwh':
yearly savings ($/kwh/year) / total owned developable planes


'high_own_devp':
high income developable plane area


'mid_own_devp':
mid income owned developable plane area (SEEDSII)


'mod_own_devp':
moderate income owned developable plane area (SEEDSII)


'low_own_devp':
low income owned developable plane area (SEEDSII)


'verylow_own_devp':
very low income owned developable plane area (SEEDSII)


'total_own_devp':
total owned developable plane area (SEEDSII)


'total_own_devpC':
total owned developable planes


'Top_3_States':
binary indicator of a census tract being in one of the top 3 adoptions per household census tracts which are CA, NV, AZ


'Savings_potential':
product of daily solar radiation (DeepSolar), total owned developable plane area (SEEDSII derived), dollars per kilo watt hour(DeepSolar)


'Income_x_College_Edu':
prduct of median household income(DeepSolar) and education_college percent (DeepSolar)


'Cost_x_Consumption':
dollars per kilo watt hour (DeepSolar) * average montlhy energy consumption (kwh)(DeepSolar)


'urban_diversity':
binary Urban locale * racial diversity(rate of race mixture) (DeepSolar)


'suburban_diversity':
binary suburban locale * racial diversity(rate of race mixture) (DeepSolar)


'rural_diversity':
binary rural locale * racial diversity(rate of race mixture) (DeepSolar)


'High_Solar_Areas':
binary indicator for census tracts above the average value for daily solar radiation


'Low_Solar_Areas':
binary indicator for census tracts below the average value for daily solar radiation


'DS_HighSolar':
binary indicator for census tracts above the threshold found by DeepSolar in daily solar radiation where adoption seemed to spike

# The below generates a data description file of this dictionary stored in data_description path. By default this will be in the same directory as this notebook

In [16]:
data_description_path = r'AddedVariableDataDict.xlsx'

pd.DataFrame(
    {
        "variables":list(cdg.DataDict.keys()),
        "Descriptions":list(cdg.DataDict.values()),
    }).to_excel(data_description_path, index=False)